# Generated by Django 2.0.1 on 2019-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
