# Generated by Django 2.0.1 on 2020-07-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200110_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('conetent', models.TextField()),
                ('time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonCfg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ding', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonProject',
            fields=[
                ('monprj_id', models.AutoField(primary_key=True, serialize=False)),
                ('monprj_name', models.CharField(max_length=50)),
                ('interview_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='monapi',
            name='monprj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MonProject'),
        ),
    ]
