# Generated by Django 2.0.1 on 2020-07-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200709_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monapi',
            old_name='conetent',
            new_name='content',
        ),
    ]
