# Generated by Django 2.0.1 on 2020-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200713_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='monapi',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
