# Generated by Django 2.0.1 on 2020-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_monapi_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.IntegerField(null=True)),
                ('api_name', models.CharField(max_length=50)),
                ('alert_details', models.TextField(null=True)),
                ('alert_time', models.CharField(max_length=50)),
            ],
        ),
    ]
