# Generated by Django 2.0.1 on 2020-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='moncfg',
            name='jingmoqi',
            field=models.IntegerField(null=True),
        ),
    ]
