# Generated by Django 2.0.1 on 2020-07-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_moncfg_jingmoqi'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='isAlert',
            field=models.IntegerField(null=True),
        ),
    ]
