# Generated by Django 2.0.1 on 2020-07-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alert_isalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
